### ISSUE TITLE
PHAR package doesn't work with relative local_directory values 

### ISSUE THREAD

**Issue by Edvinas9** [nanbando/core#32]
When _local_directory_ is defined as relative path in _nanbando.json_ file, i.e.:
`"storage": {`
`"local_directory": "./backups"`
`}`
**nanbando backup** command throws the following exception:
`[League\Flysystem\Exception]`
`Impossible to create the root directory "./backups".`

I've tried cloning nanbando/core and running pure PHP files instead of PHAR and it worked fine:
`php ../local-nanbando-copy/bin/nanbando backup`

**Comment by Edvinas9** [comment]
**FYI:** 
1. Absolute paths works without issues
2. Defining _local_directory_ in _~/.nanbando.yml_ instead of local _nanbando.json_ configuration doesn't make a difference.

**Comment by wachterjohannes** [comment]
on mac i cannot reproduce this issue. but would it help to introduce a `%project%` parameter? i will create an pr an a phar file then you can test it!

**Comment by wachterjohannes** [comment]
PR: https://github.com/nanbando/core/pull/34
PHAR: [nanbando.phar.zip](https://github.com/nanbando/core/files/428720/nanbando.phar.zip)

if this helps you i will include it into `0.2`.

**Comment by Edvinas9** [comment]
I've just tried the above nanbando.phar and it worked like a charm.

To be honest, I'd consider this as a workaround as opposed to properly fixing relative paths behaviour in different environments, but it does the trick so it would be really nice if you can get this included in **0.2** build.

Thanks Johannes!

**Comment by wachterjohannes** [comment]
no problem. it seems that the problem is the phar and relative pathes on ubuntu. maybe you have some time and find a "solid" solution.

**Comment by wachterjohannes** [comment]
i will leaf this open, but will remove it from 0.2 milestone.

**Comment by dantleech** [comment]
fyi i addressed this in PHPBench by using `getcwd`:
https://github.com/phpbench/phpbench/blob/master/lib/PhpBench.php#L70https://github.com/phpbench/phpbench/blob/master/lib/PhpBench.php#L70

**Comment by wachterjohannes** [comment]
@dantleech thats a good idea i will try this for the next release.

**Comment by wachterjohannes** [comment]
@Edvinas9 if you still have this problem with the current master phar please reopen this issue.
