### ISSUE TITLE
Display message when fetching backups

### ISSUE THREAD

**Issue by afroewis** [nanbando/core#46]
I created a backup on Environment A with a message: 
`php nanbando.phar backup -m "Automatic backup from build server"`.

Now I want to apply (restore) this backup on Environment B: 
![selection_171](https://cloud.githubusercontent.com/assets/5163630/20519180/2dc25214-b0a2-11e6-9fc4-fb720ca4d360.png)

The problem is that it's a bit difficult to distinguish the backups now. It would be great if the message of the backup would also be printed in the console.

Also: What exactly is the `label` argument good for when creating a backup?
`This label will be used to generate the filename for the backup.`

Is it really used in the filename? or is it "meta information" like the `message`?

**Comment by wachterjohannes** [comment]
the label is really used to generate the name this would also be displayed here in this screen. The message is only meta-information and stands only in the file. Which can only be read if you fetched the file.

**Comment by wachterjohannes** [comment]
I think this question is answered and can be closed. reopen if you have any related questions.
