### ISSUE TITLE
Disable auto-completion in `fetch` command

### ISSUE THREAD

**Issue by afroewis** [nanbando/core#47]
Hi,

I think that the auto-completion in the `fetch` command is a bit confusing. 

Let's assume I have 2 backups.
1) I enter `nanbando fetch`
2) This is displayed: 
```
[0] 11-11-11 2016-11-11
[1] 23-11-25 2016-11-22
```
Now I want to fetch backup nr. 1 from 2016-11-22. If I type "1", the auto-completion suggests "11-11-11 2016-11-11". If I press enter, it fetches the backup I didn't want to fetch, just because it begins with `1`. 

![selection_172](https://cloud.githubusercontent.com/assets/5163630/20519478/685bda70-b0a3-11e6-8f59-c0ddaa483d5a.png)

**Comment by wachterjohannes** [comment]
when i see the image i ask me why there is [0] and [4] ? i will check the "auto-completition"

**Comment by afroewis** [comment]
Maybe there 's [0] and [4] because I already fetched [1], [2] and [3]?

**Comment by wachterjohannes** [comment]
thats possible (: but that should be "fixed" i think...
